name: Build Flutter Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout kode
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.x'
          channel: 'stable'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run tests with detailed output
      - name: Run tests
        continue-on-error: true # Allow workflow to continue even if tests fail
        run: |
          flutter test --machine > test-results.json || true
          cat test-results.json # Output test results for debugging

      # Build APK
      - name: Build APK
        run: flutter build apk --release

      # Build AppBundle
      - name: Build AppBundle
        run: flutter build appbundle --release

      # Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7

      # Upload AppBundle artifact
      - name: Upload AppBundle
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
          retention-days: 7