name: Flutter Build

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install Flutter
      run: |
        git clone https://github.com/flutter/flutter.git -b stable
        echo "${HOME}/flutter/bin" >> $GITHUB_PATH
        echo "${HOME}/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH

    - name: Confirm Flutter Installation
      run: |
        flutter doctor

    - name: Run flutter pub get
      run: |
        flutter pub get

    - name: Build APK
      run: |
        flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk