name: Flutter Build

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: beta
        flutter-version: 3.32.0-0.3.pre  # Ganti dengan versi yang Anda butuhkan

    - name: Verify Flutter Installation
      run: flutter --version

    - name: Run flutter pub get
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk
